[versions]
agp = "8.13.2"
kotlin = "2.3.0"
okio = "3.16.4"
android-minSdk = "26"
android-compileSdk = "36"
android-targetSdk = "36"
kotlin-coroutines = "1.10.2"
logback = "1.5.22"
kotlin-logging = "7.0.13"
kotlinx-datetime = "0.7.1"
kotlinbignum = "0.3.10"
kotlinenvvar = "1.0.6"
vanniktech-maven-publish = "0.35.0"
kover = "0.9.4"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
kotlinenvvar = { module = "dev.scottpierce:kotlin-env-var", version.ref = "kotlinenvvar" }
kotlinbignum = { module = "com.ionspin.kotlin:bignum" , version.ref = "kotlinbignum" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
